addition_interiors_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#DJANGO-FILEBROWSER
from filebrowser.sites import site

from frontpage import views


#this is for django 1.6 - remove for 1.7:
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')), #grappelli urls
    url(r'^admin/', include(admin.site.urls), name='admin'),

    url(r'^inplaceeditform/', include('inplaceeditform.urls')),
    # url(r'^tinymce/', include('tinymce.urls')),
    #---------- APPS ----------#    
    url(r'', include('frontpage.urls', namespace='frontpage')),
) 

#SERVE STATIC FILES::NOT RECOMMENDED!
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()


#FOR DJANGO-DEBUG-TOOLBAR
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),   
    )

frontpage/urls.py
from django.conf.urls import patterns, url

from frontpage import views
from frontpage.views import SkillsList, RelationshipList, BrandList, AboutDetail

urlpatterns = patterns('',
                       url(r'^$', views.home_page, name='home'),

                       url(r'^thanks/$', views.thanks, name='thanks'),

                       url(r'^skills/$', SkillsList.as_view(), name='skills-list'),

                       url(r'^relationships/$', RelationshipList.as_view(),
                           name='relationship-list'),
                       url(r'^brands/$', BrandList.as_view(), name='brand-list'),
                       url(r'^about/$', AboutDetail.as_view(),
                           name='about-list'),
                       )

frontpage/models.py
from django.db import models
from django import forms
from django.core.mail import send_mail

from django.core.exceptions import ValidationError

from filebrowser.fields import FileBrowseField



# ------------------------------------------------------------
# VALIDATIONS
# ------------------------------------------------------------

def validate_only_one_instance(obj):
    model = obj.__class__
    if (model.objects.count() > 0 and
       # make sure of the correct quantity and allow re-saving existing objects
            obj.id != model.objects.get().id):
        raise ValidationError("only 1 %s can be created" % model.__name__)


def validate_only_three_instances(obj):
    model = obj.__class__
    # make sure of the correct quantity and allow re-saving existing objects
    if (model.objects.count() > 2 and
            model.objects.filter(id=obj.id).exists() == False):
        raise ValidationError("only 3 %ss can be created" % model.__name__)

def validate_only_five_instances(obj):
    model = obj.__class__
    # make sure of the correct quantity and allow re-saving existing objects
    if (model.objects.count() > 4 and
            model.objects.filter(id=obj.id).exists() == False):
        raise ValidationError("only 5 %ss can be created" % model.__name__)

# ------------------------------------------------------------
# MODELS
# ------------------------------------------------------------


class Title(models.Model):
    title = models.CharField(max_length=20, default='Addition Interiors')

    link = "Edit"

    def clean(self):
        validate_only_one_instance(self)

    def __str__(self):
        return self.title


class Slider(models.Model):
    slider_title = models.CharField(max_length=20)
    slider_text = models.TextField(max_length=200)
    slider_order = models.PositiveSmallIntegerField(
        default=1, blank=True, null=True, choices=[(1, 'first'),
                                                   (2, 'middle'), (3, 'last')])
    slider_image = FileBrowseField(
        "Image", max_length=200, directory="frontpage/sliders/", blank=True, null=True)
    # slider_image = models.ImageField(
    #     upload_to='media/frontpage/slider', blank=True, null=True,)
    link = "Edit"

    def clean(self):
        validate_only_three_instances(self)

    def __str__(self):
        return self.slider_title


class Marketing(models.Model):
    marketing_title = models.CharField(max_length=20)
    marketing_text = models.TextField(max_length=300)
    marketing_order = models.PositiveSmallIntegerField(
        default=1, blank=True, null=True, choices=[(1, 'first'),
                                                   (2, 'middle'), (3, 'last')])
    marketing_image = FileBrowseField(
        "Image", max_length=200, directory="frontpage/marketing/", blank=True, null=True)
    # marketing_image = models.ImageField(
    #    upload_to='media/frontpage/marketing', blank=True, null=True,)
    link = "Edit"

    def clean(self):
        validate_only_three_instances(self)

    def __str__(self):
        return self.marketing_title


class Feature(models.Model):
    feature_title = models.CharField(max_length=20)
    feature_subtitle = models.CharField(max_length=20)
    feature_text = models.TextField(max_length=300)
    feature_order = models.PositiveSmallIntegerField(
        default=1, blank=True, null=True, choices=[(1, 'first'),
                                                   (2, 'middle'), (3, 'last')])
    feature_image = FileBrowseField(
        "Image", max_length=200, directory="frontpage/feature/", blank=True,
        null=True)
    # feature_image = models.ImageField(
    #    upload_to='media/frontpage/feature', blank=True, null=True,)
    link = "Edit"

    def clean(self):
        validate_only_three_instances(self)

    def __str__(self):
        return self.feature_title


class Relationship(models.Model):
    relationship_title = models.CharField(max_length=40)
    relationship_comment = models.CharField(max_length=500)
    relationship_image = FileBrowseField(
        "Image", max_length=200, directory="frontpage/relationship/",
        blank=True, null=True)
    link = "Edit"

    def __str__(self):
        return self.relationship_title

class Skills(models.Model):
    skills = models.CharField(max_length=200)
    skills_order = models.PositiveSmallIntegerField(
        default=1, blank=True, null=True, choices=[(1, 'first'),
                                                   (2, 'second'), (3, 'third'), 
                                                   (4, 'fourth'), (5,'fifth'),])
    link = "Edit"

    class Meta:
        ordering = ['skills_order']
        verbose_name_plural = 'Skills'

    def clean(self):
        validate_only_five_instances(self)

    def __str__(self):
        return self.skills


class Brand(models.Model):
    brand_title = models.CharField(max_length=40)
    brand_image = FileBrowseField(
        "Image", max_length=200, directory="frontpage/brand/", blank=True,
        null=True)
    link = "Edit"

    def __str__(self):
        return self.brand_title


class About(models.Model):
    about_title = models.CharField(max_length=40)
    about_story = models.TextField(max_length=1000)
    about_image = FileBrowseField(
        "Image", max_length=200, directory="frontpage/about/",
        blank=True, null=True)
    link = "Edit"

    def __str__(self):
        return self.about_title


class Services(models.Model):
    service_title = models.CharField(max_length=200)
    service = models.TextField(max_length=400)
    link = "Edit"

    class Meta:
        verbose_name_plural = 'Services'

    def __str__(self):
        return self.service_title

frontpage/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, label='subject',
                              widget=forms.TextInput(attrs={'placeholder': 'I want a free estimate'}))
    message = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 6, 'cols': 19, 'placeholder': 'I am in need of flooring...'}))
    sender = forms.EmailField(
        required=False, widget=forms.TextInput(attrs={'placeholder': 'Email (optional)'}))
    phone = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'placeholder': 'Phone Number (optional)'}))


class SMSForm(forms.Form):
    subject = forms.CharField(max_length=100, label='subject',
                              widget=forms.TextInput(attrs={'placeholder': 'I want a free estimate'}))
    message = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 6, 'cols': 19, 'placeholder': 'Text Messsage'}))
    sender = forms.EmailField(
        required=False, widget=forms.TextInput(attrs={'placeholder': 'Email (optional)'}))
    cell = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'placeholder': 'Cell Number (optional)'}))

frontpage/views.py
from django.shortcuts import render  # get_object_or_404
from django.http import HttpResponseRedirect
from django.core.mail import send_mail  # BadHeaderError

from django.views.generic import ListView, DetailView

from frontpage.models import Slider, Marketing, Feature, Skills, Relationship, Brand, About
from frontpage.forms import ContactForm, SMSForm

# Create your views here.


def home_page(request):
    all_sliders = Slider.objects.all()
    all_marketing = Marketing.objects.all()
    all_features = Feature.objects.all()
    skill_set = Skills.objects.all()

    if request.method == 'POST' and request.POST['action'] == 'email':
        emailform = ContactForm(request.POST)
        if emailform.is_valid():
            subject = 'ADDITION INTERIORS CONTACT FORM: ' + emailform.cleaned_data['subject']
            message = emailform.cleaned_data['message']
            sender = emailform.cleaned_data['sender']
            phone = emailform.cleaned_data['phone']
            full_message = message + '\n' + 'sent from: ' + \
                sender + '\n' + 'phone number: ' + phone + '\n'

            recipients = ['xxxxxxxxxxxxxxx@gmail.com']
            send_mail(subject, full_message, sender, recipients)
            return HttpResponseRedirect('/thanks/')
    else:
        emailform = ContactForm()

    if request.method == 'POST' and request.POST['action'] == 'sms':
        smsform = SMSForm(request.POST)
        if smsform.is_valid():
            subject = 'ADDITION INTERIORS TEXT MESSAGE: ' + smsform.cleaned_data['subject']
            message = smsform.cleaned_data['message']
            sender = smsform.cleaned_data['sender']
            cell = smsform.cleaned_data['phone']
            full_message = message + '\n' + 'sent from: ' + \
                sender + '\n' + 'phone number: ' + cell + '\n'

            recipients = ['xxxxxxxxxxxxxxx@gmail.com']
            send_mail(subject, message, sender, recipients)
            return HttpResponseRedirect('/thanks/')
    else:
        smsform = SMSForm()

    context = {'sliders': all_sliders, 'marketing': all_marketing,
               'feature': all_features, 'skills': skill_set,
               # remove this clunky form dict
               'emailform': emailform, 'smsform': smsform,
               }
    return render(request, 'frontpage/home.html', context)


def thanks(request):
    return render(request, 'frontpage/thanks.html')

# --------------------------------------------------#
# STATIC PAGES - GENERIC TEMPLATES #
# --------------------------------------------------#


class SkillsList(ListView):
    model = Skills


class RelationshipList(ListView):
    model = Relationship


class BrandList(ListView):
    model = Brand


class AboutDetail(ListView):
    model = About

frontpage/templates/frontpage/about_list.html
{% extends 'frontpage/base.html' %}
{% load inplace_edit %}

{% block content %} 

{% for item in about_list %}
  <div>
  <div class='container'>
    <div class='centered'>

        <img src="{{ MEDIA_URL }}{{ item.about_image }}" alt="{{ item.about_title }}" />

        <h1 class='bg-info'> {% inplace_edit "item.about_title" adaptor="tiny" %} </h1>

        <p> {{ item.about_story | safe }} </p>
    </div>
  </div>
  </div>
{% endfor %}

{% endblock content %} 

frontpage/templates/frontpage/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        {% load staticfiles %}
        {% load admin_urls %}
        {% load inplace_edit %}

        <title>Addition Interiors</title>
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="{% static "frontpage/css/bootstrap.css" %}" />
        <!-- Custom styles for this template -->
        <link rel="stylesheet" href="{% static "frontpage/css/custom.css" %}" /> 
        {% inplace_static %}
    </head>



    <body>    

    <!-- NAVBAR
    ================================================== -->
        
        <div class="navbar-wrapper">
          <div class="container">
            <div class="navbar navbar-inverse navbar-static-top" role="navigation">
              <div class="container">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="{% url 'frontpage:home' %}"> 
                        <img src="{% static "frontpage/images/Addition-Interiors-logo-small.png" %}" class="img-responsive" />
                  </a>
                </div>
                <div class="navbar-collapse collapse">
                  <ul class="nav navbar-nav">
                    <li><a class='navlink' href="{% url 'frontpage:home' %}">Home</a></li>
                    <li><a class='navlink' href="{% url 'frontpage:relationship-list' %}">Relationships</a></li>
                    <li><a class='navlink' href="{% url 'frontpage:brand-list' %}">Brands</a></li>
                    <li><a class='navlink' href="{% url 'frontpage:about-list' %}"><span style="color:red;">Services</span></a></li>
                    
    <!-- NAVBAR DROPDOWN

                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                      </ul>
                    </li>
    ================================================== -->
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>




    <!-- CONTENT
    ================================================== -->
    <div>
        {% block content %} {% endblock %}
    </div>    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->            
        
    <!-- FOOTER -->
    <!-- ================================================== -->
    <div class='container'>
        <footer>
            <p class="pull-right"><a href="#">Back to top</a></p>
            <p>&copy; 2014 Addition Interiors &middot; <a href="{% url 'admin:index' %}">Login</a></p>
        </footer>
    </div>
    </div>

        <script src="{% static "frontpage/js/jquery-2.1.0.min.js" %}"></script>
        <script src="{% static "frontpage/js/bootstrap.min.js" %}"></script>
        <script src="{% static "frontpage/js/holder.js" %}"></script>
        {% inplace_static %}
    </body>

</html>
 

frontpage/templates/frontpage/brand_list.html
{% extends 'frontpage/base.html' %}
{% load inplace_edit %}

{% block content %} 

<br />
<p></p>
<br />

{% for item in brand_list %}
  <div class='container'>
    <div class='centered'>

        <img src="{{ MEDIA_URL }}{{ item.brand_image }}" alt="{{ item.brand_title }}" />

    </div>
  </div>
{% endfor %}

{% endblock content %} 

frontpage/templates/frontpage/home.html
{% extends 'frontpage/base.html' %}
{% load inplace_edit %}
{% load custom_tags %}

{% block content %} 


    <!-- Carousel
    ================================================== -->
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
          </ol>
        
          <div class="carousel-inner">

            
            <div class="item active">
              <img src="{{ MEDIA_URL}}{{ sliders.0.slider_image }}" alt="{{ sliders.0.slider_title }}" class="img-responsive" />
              <div class="container">
                <div class="carousel-caption">

                  <h1> {% inplace_edit "sliders.0.slider_title" %} </h1>
                  <p>{% inplace_edit "sliders.0.slider_text" %}</p>
                  
                </div>
              </div>
            </div>
        
            <div class="item">
              <img src="{{ MEDIA_URL}}{{ sliders.1.slider_image }}" alt="{{ sliders.1.slider_title }}" class="img-responsive" />
              <div class="container">
                <div class="carousel-caption">

                  <h1>{% inplace_edit "sliders.1.slider_title" %}</h1>
                  <p>{% inplace_edit "sliders.1.slider_text" %}</p>

                </div>
              </div>
            </div>
        
            <div class="item">
              <img src="{{ MEDIA_URL}}{{ sliders.2.slider_image }}" alt="{{ sliders.2.slider_title }}" class="img-responsive" />
              <div class="container">
                <div class="carousel-caption">

                  <h1>{% inplace_edit "sliders.2.slider_title" %}</h1>
                  <p>{% inplace_edit "sliders.2.slider_text" %}</p>

                  <!-- <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p> -->
                </div>
              </div>
            </div>
          </div>
          
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>
        
        </div><!-- /.carousel -->



        <!-- Marketing messaging and featurettes
    ================================================== -->
        <!-- Wrap the rest of the page in another container to center all the content. -->

        <div class="container marketing">

          <!-- Three columns of text below the carousel -->
          <div class="row">
            <div class="col-lg-4">
            <!--INTENDED IMAGE SIZE 150x150 -->
              <img class="marketing-img img-circle img-responsive" src="{{ MEDIA_URL}}{{ marketing.0.marketing_image }}" alt="{{ marketing.0.marketing_title }}" />
              
              <h2>{% inplace_edit "marketing.0.marketing_title" %}</h2>
              <p>{% inplace_edit "marketing.0.marketing_text" %}</p>
              
              <form action="" method="POST">
              {% csrf_token %}
              {% csrf_token %}
              {% for field in smsform %}
                  {{ field }}<span style='color:red;'>{{ field.errors }}</span>
                  <p></p>
              {% endfor %}
                  <input type="hidden" name="action" value="sms">
                  <input type="submit" class="btn btn-primary btn-lg" value="Send Text Message">
              </form>
              
            </div>
            <!-- /.col-lg-4 -->

            <div class="col-lg-4">
              <img class="marketing-img img-circle img-responsive" src="{{ MEDIA_URL}}{{ marketing.1.marketing_image }}" alt="{{ marketing.1.marketing_title }}" />
              <h2>{% inplace_edit "marketing.1.marketing_title" %}</h2>
              <p>{% inplace_edit "marketing.1.marketing_text" %}</p>
              
              <form action="" method="POST">
              {% csrf_token %}
              {% csrf_token %}
              {% for field in emailform %}
                  {{ field }}<span style='color:red;'>{{ field.errors }}</span>
                  <p></p>
              {% endfor %}
                  <input type="hidden" name="action" value="email">
                  <input type="submit" class="btn btn-primary btn-lg" value="Send Email">
              </form>

            </div>
            <!-- /.col-lg-4 -->

            <div class="col-lg-4">
              <img class="marketing-img img-circle img-responsive" src="{{ MEDIA_URL}}{{ marketing.2.marketing_image }}" alt="{{ marketing.2.marketing_title }}" />
              <h2>{% inplace_edit "marketing.2.marketing_title" %}</h2>
              <p>{% inplace_edit "marketing.2.marketing_text" %}</p>
              <br />
                {% for item in skills %}
                <h4 class="bg-info"> {% inplace_edit "item.skills" %} </h4>
                <p></p>
                {% endfor %}
              <br />
              <p><a class="btn btn-default btn-lg btn-block" href="{% url 'frontpage:about-list' %}" role="button">Details &raquo;</a></p>
            </div>
            <!-- /.col-lg-4 -->
          </div>
          <!-- /.row -->


          <!-- START THE FEATURETTES -->

          <hr class="featurette-divider">

          <div class="row featurette">
            <div class="col-md-7">
              <h2 class="featurette-heading"> {% inplace_edit "feature.0.feature_title" %} <span class="text-muted"> {% inplace_edit "feature.0.feature_subtitle" %} </span></h2>
              <p class="lead"> {% inplace_edit "feature.0.feature_text" %} </p>
            </div>
            <div class="col-md-5">
            <!--INTENDED IMAGE SIZE 500x500 -->
              <img class="featurette-image img-responsive" src="{{ MEDIA_URL}}{{ feature.0.feature_image }}" alt="{{ feature.0.feature_title }}" />
            </div>
          </div>

          <hr class="featurette-divider">

          <div class="row featurette">
            <div class="col-md-5">
            <!--INTENDED IMAGE SIZE 150x150 -->
              <img class="featurette-image img-responsive" src="{{ MEDIA_URL}}{{ feature.1.feature_image }}" alt="{{ feature.1.feature_title }}" />
            </div>
            <div class="col-md-7">
              <h2 class="featurette-heading"> {% inplace_edit "feature.1.feature_title" %} <span class="text-muted"> {% inplace_edit "feature.1.feature_subtitle" %} </span></h2>
              <p class="lead"> {% inplace_edit "feature.1.feature_text" %} </p>
            </div>
          </div>

          <hr class="featurette-divider">

          <div class="row featurette">
            <div class="col-md-7">
              <h2 class="featurette-heading"> {% inplace_edit "feature.2.feature_title" %} <span class="text-muted"> {% inplace_edit "feature.2.feature_subtitle" %} </span></h2>
              <p class="lead"> {% inplace_edit "feature.2.feature_text" %} </p>
            </div>
            <div class="col-md-5">
            <!--INTENDED IMAGE SIZE 150x150 -->
              <img class="featurette-image img-responsive" src="{{ MEDIA_URL}}{{ feature.2.feature_image }}" alt="{{ feature.2.feature_title }}" />
            </div>
          </div>

          <hr class="featurette-divider">

          <!-- /END THE FEATURETTES -->





{% endblock content %} 

frontpage/templates/frontpage/relationship.html
{% extends 'frontpage/base.html' %}
{% load inplace_edit %}

{% block content %} 

<div>
  <h1> PEOPLE LOVE WORKING WITH US </h1>
</div>
<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading">  <span class="text-muted"> {% inplace_edit "feature.2.feature_subtitle" %} </span></h2>
      <p class="lead"> {% inplace_edit "feature.2.feature_text" %} </p>
  </div>
  <div class="col-md-5">
    <!--INTENDED IMAGE SIZE 150x150 -->
    <img class="featurette-image img-responsive" src="{{ MEDIA_URL}}{{ feature.2.feature_image }}" alt="{{ feature.2.feature_title }}" />
  </div>
</div>


{% endblock content %} 

frontpage/templates/frontpage/relationship_list.html
{% extends 'frontpage/base.html' %}
{% load inplace_edit %}

{% block content %} 

<br />
<p></p>
<br />

{% for item in relationship_list %}
	<div class='container centered' style='margin-left: 3em;'>
		<div class='bubble-centered'>
			<p>	{% inplace_edit "item.relationship_comment" %} </p>
		</div>
		<br />
		<p>	{% inplace_edit "item.relationship_title" %} </p>
	</div>

	<hr>
{% endfor %}

{% endblock content %} 

frontpage/templates/frontpage/site_title.html
{{ title }}

frontpage/templates/frontpage/skills_list.html
{% load inplace_edit %}

{% block skills %} 

TEST

	{% for item in skills_list %}

		<h3 style='background-color:yellow;'> {% inplace_edit "item.skills" %} </h3>

	{% endfor %}

{% endblock %} 

              

frontpage/templates/frontpage/sms.html
{% block sms %}
      
    {% if errors %}
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
  
    <form action="" method="post">
    {% csrf_token %}
        <input type="text" name="subject" placeholder="I want a free estimate...">
        <p></p>
        <input type="text" name="email" placeholder="email address (optional)">
        <p></p>
        <textarea name="message" placeholder="send me a text message..."></textarea>
        <br />
        <input type="submit" value="Submit">
    </form>

{% endblock %}

frontpage/templates/frontpage/thanks.html
{% extends 'frontpage/base.html' %}

    {% block content %}
    <div class='container'>
      <h1>Thanks for contacting us!</h1>

      <h2>Be sure and ask for your <span style="color:red; background:"><em>10%</em></span> discount!</h2>
      <p>
      <br />
      </p>
	</div>  
    {% endblock %}